### PR TITLE
Kredobank plugin

### PR DESCRIPTION
**Pull request by vpetrovych**

### CODE REVIEW

**Comment by vpetrovych** [comment]
@skvav  please review

**Comment by skvav** [comment]
@vpetrovych thanks. But we already have sync with Kredobank in the app :) Does it not work?

**Comment by vpetrovych** [comment]
@skvav  It doesn't. I've left a few emails and messages in telegram, but it didn't get anywhere.

**Comment by vpetrovych** [comment]
Here's the error I get. I left the issue with your in-app support at the end of December
image

**Comment by vpetrovych** [comment]
Closing in favour of zenmoney own kredobank plugin

**Pull request closed without merging**
